# Generated by Django 4.2.7 on 2026-02-12 06:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter'), ('admin', 'Admin/Placement Officer')], default='student', help_text='User role in the system', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code for branch (e.g., CSE, ECE)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of the branch', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the branch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Brief description of the company')),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('industry', models.CharField(help_text='Industry sector (e.g., IT, Finance, Manufacturing)', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company_logos/')),
                ('location', models.CharField(help_text='Headquarters or primary location', max_length=200)),
                ('contact_person', models.CharField(help_text='Name of HR/recruitment contact person', max_length=100)),
                ('contact_email', models.EmailField(help_text='Contact email for recruitment queries', max_length=254)),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether company is approved by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(help_text='Recruiter who manages this company', limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(help_text='University enrollment/registration number', max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Student's date of birth", null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('CHEM', 'Chemical Engineering'), ('OTHER', 'Other')], help_text='Branch/Department', max_length=10)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], help_text='Current year of study', max_length=1)),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Cumulative Grade Point Average (0-10 scale)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('backlogs', models.IntegerField(default=0, help_text='Number of active backlogs/arrears', validators=[django.core.validators.MinValueValidator(0)])),
                ('tenth_percentage', models.DecimalField(decimal_places=2, help_text='10th standard percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, help_text='12th standard percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('skills', models.TextField(help_text='Comma-separated list of skills (e.g., Python, Java, SQL)')),
                ('certifications', models.TextField(blank=True, help_text='List of certifications and courses completed', null=True)),
                ('projects', models.TextField(blank=True, help_text='Brief description of projects completed', null=True)),
                ('resume', models.FileField(blank=True, help_text='Upload resume in PDF format only', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('resume_uploaded_at', models.DateTimeField(blank=True, help_text='Timestamp when resume was uploaded', null=True)),
                ('is_placed', models.BooleanField(default=False, help_text='Whether student has been placed')),
                ('placement_company', models.CharField(blank=True, help_text='Company where student got placed', max_length=200, null=True)),
                ('placement_package', models.DecimalField(blank=True, decimal_places=2, help_text='Annual package in lakhs', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-cgpa', 'backlogs'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Drive title (e.g., 'Winter Placements 2024')", max_length=200)),
                ('description', models.TextField(help_text='Description and details of the drive')),
                ('start_date', models.DateField(help_text='Drive start date')),
                ('end_date', models.DateField(help_text='Drive end date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether drive is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, help_text='Companies participating in this drive', related_name='drives', to='placement.company')),
                ('created_by', models.ForeignKey(help_text='Admin who created this drive', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Drive',
                'verbose_name_plural': 'Placement Drives',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title/position', max_length=200)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('internship', 'Internship'), ('part_time', 'Part Time')], default='full_time', help_text='Type of employment', max_length=20)),
                ('location', models.CharField(help_text='Job location(s)', max_length=200)),
                ('package_min', models.DecimalField(decimal_places=2, help_text='Minimum package/stipend in lakhs per annum', max_digits=10)),
                ('package_max', models.DecimalField(decimal_places=2, help_text='Maximum package/stipend in lakhs per annum', max_digits=10)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, help_text='Minimum CGPA required', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('maximum_backlogs', models.IntegerField(default=0, help_text='Maximum number of backlogs allowed', validators=[django.core.validators.MinValueValidator(0)])),
                ('allowed_years', models.CharField(default='4', help_text="Comma-separated years eligible (e.g., '3,4' for third and fourth year)", max_length=20)),
                ('required_skills', models.TextField(help_text='Skills required for this position')),
                ('deadline', models.DateTimeField(help_text='Application deadline')),
                ('vacancies', models.IntegerField(default=1, help_text='Number of positions available', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether job is currently accepting applications')),
                ('bond_details', models.TextField(blank=True, help_text='Bond or service agreement details', null=True)),
                ('selection_process', models.TextField(blank=True, help_text='Details about selection rounds (written test, interview, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_branches', models.ManyToManyField(blank=True, help_text='Branches eligible for this job (leave empty for all branches)', related_name='jobs', to='placement.branch')),
                ('company', models.ForeignKey(help_text='Company posting this job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='placement.company')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted/Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Student')], default='pending', help_text='Current application status', max_length=20)),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter or message to recruiter', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter_notes', models.TextField(blank=True, help_text='Notes from recruiter (visible to admin only)', null=True)),
                ('job', models.ForeignKey(help_text='Job applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.jobposting')),
                ('student', models.ForeignKey(help_text='Student who applied', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.studentprofile')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'job')},
            },
        ),
    ]
